### ISSUE TITLE
Clicking a specific leaderboard doesn't take you to that specific leaderboard

### ISSUE THREAD

**Issue by ForrestMcIntyre** [BlueHerons/StatTracker#89]
There are no id attr on the leaderboards for the nav to hook onto

**Comment by johnluetke** [comment]
There *should* be a anchors.

If I remember correctly, part of this is caused by the ajax loading the content late, and the page height changing after the browser jumps to the anchor.

**Comment by phthoruth** [comment]
I was about to suggest this!
Once reason is the values shown dont exactly match the specific leaderboard.
On a PC usually look at each 'upcoming' and do a search based on days remaining.
Partially because the badges are not clear... especially the ones that noone has ever gotten.
So that could be improved too... make the badge clear with text in a mouse over or something.
The days remaining doesnt always match up.  e.g. it says 334.5 days remaining, but in the detailed section it has a different number.  Then I search by percentage to get to the detals.
When it works, I search a second time to go to the top.  This doesnt work for phones and I have to manually scroll down and back up.
I do this for all upcoming badges.

I take note of my progress on the upcoming badges daily, and want to see a day or more of progress on the ones I care about.

**Comment by johnluetke** [comment]
every badge has been entered, so they shouldn't be any more "unknown" (solid colors) left.
